msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2022-09-26 07:58-0500\n"
"PO-Revision-Date: 2022-09-28 19:56\n"
"Last-Translator: \n"
"Language-Team: Russian, Belarus\n"
"Language: ru_BY\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: duplicity\n"
"X-Crowdin-Project-ID: 539508\n"
"X-Crowdin-Language: ru-BY\n"
"X-Crowdin-File: /main/po/duplicity.pot\n"
"X-Crowdin-File-ID: 6\n"

#: ../bin/duplicity:107
msgid "INT intercepted...exiting."
msgstr "Перехват INT...выполняется выход."

#: ../bin/duplicity:115
#, python-format
msgid "GPG error detail: %s"
msgstr "Подробности ошибки GPG: %s"

#: ../bin/duplicity:125
#, python-format
msgid "User error detail: %s"
msgstr "Сведения ошибки пользователя: %s"

#: ../bin/duplicity:135
#, python-format
msgid "Backend error detail: %s"
msgstr "Подробности об ошибке в заглушке: %s"

#: ../bin/rdiffdir:64 ../duplicity/commandline.py:240
#, python-format
msgid "Error opening file %s"
msgstr "Ошибка открытия файла %s"

#: ../bin/rdiffdir:131
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr "Файл %s уже существует и не будет перезаписан."

#: ../duplicity/tempdir.py:160
#, python-format
msgid "Using temporary directory %s"
msgstr "Используется временный каталог %s"

#: ../duplicity/tempdir.py:204
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Регистрация (mktemp) временного файла %s"

#: ../duplicity/tempdir.py:226
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Регистрация (mkstemp) временного файла %s"

#: ../duplicity/tempdir.py:258
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Удаление временного файла %s"

#: ../duplicity/tempdir.py:261
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr "Попытка удалить неизвестный временный файл %s - похоже, что это ошибка в программе."

#: ../duplicity/tempdir.py:280
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Удаление всё ещё нужного временного файла %s"

#: ../duplicity/tempdir.py:283
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "Не удалось очистить временный файл %s"

#: ../duplicity/tempdir.py:288
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr "Не удалось очистить временный каталог %s - похоже, что это ошибка в программе."

#: ../duplicity/backend.py:102
#, python-format
msgid "Import of %s %s"
msgstr "Импортирование %s %s"

#: ../duplicity/backend.py:211
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Невозможно инициализиовать внутренний интерфейс: %s"

#: ../duplicity/backend.py:403
#, python-format
msgid "Backtrace of previous error: %s"
msgstr ""

#: ../duplicity/backend.py:419
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr ""

#: ../duplicity/backend.py:423
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backend.py:517
#, python-format
msgid "Reading results of '%s'"
msgstr "Чтение результата '%s'"

#: ../duplicity/backend.py:543
#, python-format
msgid "Writing %s"
msgstr "Записывается %s"

#: ../duplicity/backend.py:584
#, python-format
msgid "File %s not found locally after get from backend"
msgstr ""

#: ../duplicity/gpg_error_codes.py:8
msgid "Success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:9
msgid "General error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:10
msgid "Unknown packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:11
msgid "Unknown version in packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:12
msgid "Invalid public key algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:13
msgid "Invalid digest algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:14
msgid "Bad public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:15
msgid "Bad secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:16
msgid "Bad signature"
msgstr ""

#: ../duplicity/gpg_error_codes.py:17
msgid "No public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:18
msgid "Checksum error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:19
msgid "Bad passphrase"
msgstr ""

#: ../duplicity/gpg_error_codes.py:20
msgid "Invalid cipher algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:21
msgid "Cannot open keyring"
msgstr ""

#: ../duplicity/gpg_error_codes.py:22
msgid "Invalid packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:23
msgid "Invalid armor"
msgstr ""

#: ../duplicity/gpg_error_codes.py:24
msgid "No user ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:25
msgid "No secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:26
msgid "Wrong secret key used"
msgstr ""

#: ../duplicity/gpg_error_codes.py:27
msgid "Bad session key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:28
msgid "Unknown compression algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:29
msgid "Number is not prime"
msgstr ""

#: ../duplicity/gpg_error_codes.py:30
msgid "Invalid encoding method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:31
msgid "Invalid encryption scheme"
msgstr ""

#: ../duplicity/gpg_error_codes.py:32
msgid "Invalid signature scheme"
msgstr ""

#: ../duplicity/gpg_error_codes.py:33
msgid "Invalid attribute"
msgstr ""

#: ../duplicity/gpg_error_codes.py:34
msgid "No value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:35
msgid "Not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:36
msgid "Value not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:37
msgid "Syntax error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:38
msgid "Bad MPI value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:39
msgid "Invalid passphrase"
msgstr ""

#: ../duplicity/gpg_error_codes.py:40
msgid "Invalid signature class"
msgstr ""

#: ../duplicity/gpg_error_codes.py:41
msgid "Resources exhausted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:42
msgid "Invalid keyring"
msgstr ""

#: ../duplicity/gpg_error_codes.py:43
msgid "Trust DB error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:44
msgid "Bad certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:45
msgid "Invalid user ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:46
msgid "Unexpected error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:47
msgid "Time conflict"
msgstr ""

#: ../duplicity/gpg_error_codes.py:48
msgid "Keyserver error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:49
msgid "Wrong public key algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:50
msgid "Tribute to D. A."
msgstr ""

#: ../duplicity/gpg_error_codes.py:51
msgid "Weak encryption key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:52
msgid "Invalid key length"
msgstr ""

#: ../duplicity/gpg_error_codes.py:53
msgid "Invalid argument"
msgstr ""

#: ../duplicity/gpg_error_codes.py:54
msgid "Syntax error in URI"
msgstr ""

#: ../duplicity/gpg_error_codes.py:55
msgid "Invalid URI"
msgstr ""

#: ../duplicity/gpg_error_codes.py:56
msgid "Network error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:57
msgid "Unknown host"
msgstr ""

#: ../duplicity/gpg_error_codes.py:58
msgid "Selftest failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:59
msgid "Data not encrypted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:60
msgid "Data not processed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:61
msgid "Unusable public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:62
msgid "Unusable secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:63
msgid "Invalid value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:64
msgid "Bad certificate chain"
msgstr ""

#: ../duplicity/gpg_error_codes.py:65
msgid "Missing certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:66
msgid "No data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:67
msgid "Bug"
msgstr ""

#: ../duplicity/gpg_error_codes.py:68
msgid "Not supported"
msgstr ""

#: ../duplicity/gpg_error_codes.py:69
msgid "Invalid operation code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:70
msgid "Timeout"
msgstr ""

#: ../duplicity/gpg_error_codes.py:71
msgid "Internal error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:72
msgid "EOF (gcrypt)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:73
msgid "Invalid object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:74
msgid "Provided object is too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:75
msgid "Provided object is too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:76
msgid "Missing item in object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:77
msgid "Not implemented"
msgstr ""

#: ../duplicity/gpg_error_codes.py:78
msgid "Conflicting use"
msgstr ""

#: ../duplicity/gpg_error_codes.py:79
msgid "Invalid cipher mode"
msgstr ""

#: ../duplicity/gpg_error_codes.py:80
msgid "Invalid flag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:81
msgid "Invalid handle"
msgstr ""

#: ../duplicity/gpg_error_codes.py:82
msgid "Result truncated"
msgstr ""

#: ../duplicity/gpg_error_codes.py:83
msgid "Incomplete line"
msgstr ""

#: ../duplicity/gpg_error_codes.py:84
msgid "Invalid response"
msgstr ""

#: ../duplicity/gpg_error_codes.py:85
msgid "No agent running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:86
msgid "Agent error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:87
msgid "Invalid data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:88
msgid "Unspecific Assuan server fault"
msgstr ""

#: ../duplicity/gpg_error_codes.py:89
msgid "General Assuan error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:90
msgid "Invalid session key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:91
msgid "Invalid S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:92
msgid "Unsupported algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:93
msgid "No pinentry"
msgstr ""

#: ../duplicity/gpg_error_codes.py:94
msgid "pinentry error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:95
msgid "Bad PIN"
msgstr ""

#: ../duplicity/gpg_error_codes.py:96
msgid "Invalid name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:97
msgid "Bad data"
msgstr ""

#: ../duplicity/gpg_error_codes.py:98
msgid "Invalid parameter"
msgstr ""

#: ../duplicity/gpg_error_codes.py:99
msgid "Wrong card"
msgstr ""

#: ../duplicity/gpg_error_codes.py:100
msgid "No dirmngr"
msgstr ""

#: ../duplicity/gpg_error_codes.py:101
msgid "dirmngr error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:102
msgid "Certificate revoked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:103
msgid "No CRL known"
msgstr ""

#: ../duplicity/gpg_error_codes.py:104
msgid "CRL too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:105
msgid "Line too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:106
msgid "Not trusted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:107
msgid "Operation cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:108
msgid "Bad CA certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:109
msgid "Certificate expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:110
msgid "Certificate too young"
msgstr ""

#: ../duplicity/gpg_error_codes.py:111
msgid "Unsupported certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:112
msgid "Unknown S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:113
msgid "Unsupported protection"
msgstr ""

#: ../duplicity/gpg_error_codes.py:114
msgid "Corrupted protection"
msgstr ""

#: ../duplicity/gpg_error_codes.py:115
msgid "Ambiguous name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:116
msgid "Card error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:117
msgid "Card reset required"
msgstr ""

#: ../duplicity/gpg_error_codes.py:118
msgid "Card removed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:119
msgid "Invalid card"
msgstr ""

#: ../duplicity/gpg_error_codes.py:120
msgid "Card not present"
msgstr ""

#: ../duplicity/gpg_error_codes.py:121
msgid "Not confirmed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:122
msgid "Configuration error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:123
msgid "No policy match"
msgstr ""

#: ../duplicity/gpg_error_codes.py:124
msgid "Invalid index"
msgstr ""

#: ../duplicity/gpg_error_codes.py:125
msgid "Invalid ID"
msgstr ""

#: ../duplicity/gpg_error_codes.py:126
msgid "No SmartCard daemon"
msgstr ""

#: ../duplicity/gpg_error_codes.py:127
msgid "SmartCard daemon error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:128
msgid "Unsupported protocol"
msgstr ""

#: ../duplicity/gpg_error_codes.py:129
msgid "Bad PIN method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:130
msgid "Card not initialized"
msgstr ""

#: ../duplicity/gpg_error_codes.py:131
msgid "Unsupported operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:132
msgid "Wrong key usage"
msgstr ""

#: ../duplicity/gpg_error_codes.py:133
msgid "Nothing found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:134
msgid "Wrong blob type"
msgstr ""

#: ../duplicity/gpg_error_codes.py:135
msgid "Missing value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:136
msgid "Hardware problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:137
msgid "PIN blocked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:138
msgid "Conditions of use not satisfied"
msgstr ""

#: ../duplicity/gpg_error_codes.py:139
msgid "PINs are not synced"
msgstr ""

#: ../duplicity/gpg_error_codes.py:140
msgid "Invalid CRL"
msgstr ""

#: ../duplicity/gpg_error_codes.py:141
msgid "BER error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:142
msgid "Invalid BER"
msgstr ""

#: ../duplicity/gpg_error_codes.py:143
msgid "Element not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:144
msgid "Identifier not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:145
msgid "Invalid tag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:146
msgid "Invalid length"
msgstr ""

#: ../duplicity/gpg_error_codes.py:147
msgid "Invalid key info"
msgstr ""

#: ../duplicity/gpg_error_codes.py:148
msgid "Unexpected tag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:149
msgid "Not DER encoded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:150
msgid "No CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:151
msgid "Invalid CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:152
msgid "Unknown CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:153
msgid "Unsupported CMS object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:154
msgid "Unsupported encoding"
msgstr ""

#: ../duplicity/gpg_error_codes.py:155
msgid "Unsupported CMS version"
msgstr ""

#: ../duplicity/gpg_error_codes.py:156
msgid "Unknown algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:157
msgid "Invalid crypto engine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:158
msgid "Public key not trusted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:159
msgid "Decryption failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:160
msgid "Key expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:161
msgid "Signature expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:162
msgid "Encoding problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:163
msgid "Invalid state"
msgstr ""

#: ../duplicity/gpg_error_codes.py:164
msgid "Duplicated value"
msgstr ""

#: ../duplicity/gpg_error_codes.py:165
msgid "Missing action"
msgstr ""

#: ../duplicity/gpg_error_codes.py:166
msgid "ASN.1 module not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:167
msgid "Invalid OID string"
msgstr ""

#: ../duplicity/gpg_error_codes.py:168
msgid "Invalid time"
msgstr ""

#: ../duplicity/gpg_error_codes.py:169
msgid "Invalid CRL object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:170
msgid "Unsupported CRL version"
msgstr ""

#: ../duplicity/gpg_error_codes.py:171
msgid "Invalid certificate object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:172
msgid "Unknown name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:173
msgid "A locale function failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:174
msgid "Not locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:175
msgid "Protocol violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:176
msgid "Invalid MAC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:177
msgid "Invalid request"
msgstr ""

#: ../duplicity/gpg_error_codes.py:178
msgid "Unknown extension"
msgstr ""

#: ../duplicity/gpg_error_codes.py:179
msgid "Unknown critical extension"
msgstr ""

#: ../duplicity/gpg_error_codes.py:180
msgid "Locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:181
msgid "Unknown option"
msgstr ""

#: ../duplicity/gpg_error_codes.py:182
msgid "Unknown command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:183
msgid "Not operational"
msgstr ""

#: ../duplicity/gpg_error_codes.py:184
msgid "No passphrase given"
msgstr ""

#: ../duplicity/gpg_error_codes.py:185
msgid "No PIN given"
msgstr ""

#: ../duplicity/gpg_error_codes.py:186
msgid "Not enabled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:187
msgid "No crypto engine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:188
msgid "Missing key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:189
msgid "Too many objects"
msgstr ""

#: ../duplicity/gpg_error_codes.py:190
msgid "Limit reached"
msgstr ""

#: ../duplicity/gpg_error_codes.py:191
msgid "Not initialized"
msgstr ""

#: ../duplicity/gpg_error_codes.py:192
msgid "Missing issuer certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:193
msgid "No keyserver available"
msgstr ""

#: ../duplicity/gpg_error_codes.py:194
msgid "Invalid elliptic curve"
msgstr ""

#: ../duplicity/gpg_error_codes.py:195
msgid "Unknown elliptic curve"
msgstr ""

#: ../duplicity/gpg_error_codes.py:196
msgid "Duplicated key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:197
msgid "Ambiguous result"
msgstr ""

#: ../duplicity/gpg_error_codes.py:198
msgid "No crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:199
msgid "Wrong crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:200
msgid "Bad crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:201
msgid "Conflict in the crypto context"
msgstr ""

#: ../duplicity/gpg_error_codes.py:202
msgid "Broken public key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:203
msgid "Broken secret key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:204
msgid "Invalid MAC algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:205
msgid "Operation fully cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:206
msgid "Operation not yet finished"
msgstr ""

#: ../duplicity/gpg_error_codes.py:207
msgid "Buffer too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:208
msgid "Invalid length specifier in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:209
msgid "String too long in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:210
msgid "Unmatched parentheses in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:211
msgid "S-expression not canonical"
msgstr ""

#: ../duplicity/gpg_error_codes.py:212
msgid "Bad character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:213
msgid "Bad quotation in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:214
msgid "Zero prefix in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:215
msgid "Nested display hints in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:216
msgid "Unmatched display hints"
msgstr ""

#: ../duplicity/gpg_error_codes.py:217
msgid "Unexpected reserved punctuation in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:218
msgid "Bad hexadecimal character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:219
msgid "Odd hexadecimal numbers in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:220
msgid "Bad octal character in S-expression"
msgstr ""

#: ../duplicity/gpg_error_codes.py:221
msgid "All subkeys are expired or revoked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:222
msgid "Database is corrupted"
msgstr ""

#: ../duplicity/gpg_error_codes.py:223
msgid "Server indicated a failure"
msgstr ""

#: ../duplicity/gpg_error_codes.py:224
msgid "No name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:225
msgid "No key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:226
msgid "Legacy key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:227
msgid "Request too short"
msgstr ""

#: ../duplicity/gpg_error_codes.py:228
msgid "Request too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:229
msgid "Object is in termination state"
msgstr ""

#: ../duplicity/gpg_error_codes.py:230
msgid "No certificate chain"
msgstr ""

#: ../duplicity/gpg_error_codes.py:231
msgid "Certificate is too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:232
msgid "Invalid record"
msgstr ""

#: ../duplicity/gpg_error_codes.py:233
msgid "The MAC does not verify"
msgstr ""

#: ../duplicity/gpg_error_codes.py:234
msgid "Unexpected message"
msgstr ""

#: ../duplicity/gpg_error_codes.py:235
msgid "Compression or decompression failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:236
msgid "A counter would wrap"
msgstr ""

#: ../duplicity/gpg_error_codes.py:237
msgid "Fatal alert message received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:238
msgid "No cipher algorithm"
msgstr ""

#: ../duplicity/gpg_error_codes.py:239
msgid "Missing client certificate"
msgstr ""

#: ../duplicity/gpg_error_codes.py:240
msgid "Close notification received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:241
msgid "Ticket expired"
msgstr ""

#: ../duplicity/gpg_error_codes.py:242
msgid "Bad ticket"
msgstr ""

#: ../duplicity/gpg_error_codes.py:243
msgid "Unknown identity"
msgstr ""

#: ../duplicity/gpg_error_codes.py:244
msgid "Bad certificate message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:245
msgid "Bad certificate request message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:246
msgid "Bad certificate verify message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:247
msgid "Bad change cipher message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:248
msgid "Bad client hello message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:249
msgid "Bad server hello message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:250
msgid "Bad server hello done message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:251
msgid "Bad finished message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:252
msgid "Bad server key exchange message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:253
msgid "Bad client key exchange message in handshake"
msgstr ""

#: ../duplicity/gpg_error_codes.py:254
msgid "Bogus string"
msgstr ""

#: ../duplicity/gpg_error_codes.py:255
msgid "Forbidden"
msgstr ""

#: ../duplicity/gpg_error_codes.py:256
msgid "Key disabled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:257
msgid "Not possible with a card based key"
msgstr ""

#: ../duplicity/gpg_error_codes.py:258
msgid "Invalid lock object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:259
msgid "True"
msgstr ""

#: ../duplicity/gpg_error_codes.py:260
msgid "False"
msgstr ""

#: ../duplicity/gpg_error_codes.py:261
msgid "General IPC error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:262
msgid "IPC accept call failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:263
msgid "IPC connect call failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:264
msgid "Invalid IPC response"
msgstr ""

#: ../duplicity/gpg_error_codes.py:265
msgid "Invalid value passed to IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:266
msgid "Incomplete line passed to IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:267
msgid "Line passed to IPC too long"
msgstr ""

#: ../duplicity/gpg_error_codes.py:268
msgid "Nested IPC commands"
msgstr ""

#: ../duplicity/gpg_error_codes.py:269
msgid "No data callback in IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:270
msgid "No inquire callback in IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:271
msgid "Not an IPC server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:272
msgid "Not an IPC client"
msgstr ""

#: ../duplicity/gpg_error_codes.py:273
msgid "Problem starting IPC server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:274
msgid "IPC read error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:275
msgid "IPC write error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:276
msgid "Too much data for IPC layer"
msgstr ""

#: ../duplicity/gpg_error_codes.py:277
msgid "Unexpected IPC command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:278
msgid "Unknown IPC command"
msgstr ""

#: ../duplicity/gpg_error_codes.py:279
msgid "IPC syntax error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:280
msgid "IPC call has been cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:281
msgid "No input source for IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:282
msgid "No output source for IPC"
msgstr ""

#: ../duplicity/gpg_error_codes.py:283
msgid "IPC parameter error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:284
msgid "Unknown IPC inquire"
msgstr ""

#: ../duplicity/gpg_error_codes.py:285
msgid "Crypto engine too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:286
msgid "Screen or window too small"
msgstr ""

#: ../duplicity/gpg_error_codes.py:287
msgid "Screen or window too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:288
msgid "Required environment variable not set"
msgstr ""

#: ../duplicity/gpg_error_codes.py:289
msgid "User ID already exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:290
msgid "Name already exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:291
msgid "Duplicated name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:292
msgid "Object is too young"
msgstr ""

#: ../duplicity/gpg_error_codes.py:293
msgid "Object is too old"
msgstr ""

#: ../duplicity/gpg_error_codes.py:294
msgid "Unknown flag"
msgstr ""

#: ../duplicity/gpg_error_codes.py:295
msgid "Invalid execution order"
msgstr ""

#: ../duplicity/gpg_error_codes.py:296
msgid "Already fetched"
msgstr ""

#: ../duplicity/gpg_error_codes.py:297
msgid "Try again later"
msgstr ""

#: ../duplicity/gpg_error_codes.py:298
msgid "Wrong name"
msgstr ""

#: ../duplicity/gpg_error_codes.py:299
msgid "Not authenticated"
msgstr ""

#: ../duplicity/gpg_error_codes.py:300
msgid "Bad authentication"
msgstr ""

#: ../duplicity/gpg_error_codes.py:301
msgid "No Keybox daemon running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:302
msgid "Keybox daemon error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:303
msgid "Service is not running"
msgstr ""

#: ../duplicity/gpg_error_codes.py:304
msgid "Service error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:305
msgid "System bug detected"
msgstr ""

#: ../duplicity/gpg_error_codes.py:306
msgid "Unknown DNS error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:307
msgid "Invalid DNS section"
msgstr ""

#: ../duplicity/gpg_error_codes.py:308
msgid "Invalid textual address form"
msgstr ""

#: ../duplicity/gpg_error_codes.py:309
msgid "Missing DNS query packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:310
msgid "Missing DNS answer packet"
msgstr ""

#: ../duplicity/gpg_error_codes.py:311
msgid "Connection closed in DNS"
msgstr ""

#: ../duplicity/gpg_error_codes.py:312
msgid "Verification failed in DNS"
msgstr ""

#: ../duplicity/gpg_error_codes.py:313
msgid "DNS Timeout"
msgstr ""

#: ../duplicity/gpg_error_codes.py:314
msgid "General LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:315
msgid "General LDAP attribute error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:316
msgid "General LDAP name error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:317
msgid "General LDAP security error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:318
msgid "General LDAP service error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:319
msgid "General LDAP update error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:320
msgid "Experimental LDAP error code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:321
msgid "Private LDAP error code"
msgstr ""

#: ../duplicity/gpg_error_codes.py:322
msgid "Other general LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:323
msgid "LDAP connecting failed (X)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:324
msgid "LDAP referral limit exceeded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:325
msgid "LDAP client loop"
msgstr ""

#: ../duplicity/gpg_error_codes.py:326
msgid "No LDAP results returned"
msgstr ""

#: ../duplicity/gpg_error_codes.py:327
msgid "LDAP control not found"
msgstr ""

#: ../duplicity/gpg_error_codes.py:328
msgid "Not supported by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:329
msgid "LDAP connect error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:330
msgid "Out of memory in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:331
msgid "Bad parameter to an LDAP routine"
msgstr ""

#: ../duplicity/gpg_error_codes.py:332
msgid "User cancelled LDAP operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:333
msgid "Bad LDAP search filter"
msgstr ""

#: ../duplicity/gpg_error_codes.py:334
msgid "Unknown LDAP authentication method"
msgstr ""

#: ../duplicity/gpg_error_codes.py:335
msgid "Timeout in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:336
msgid "LDAP decoding error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:337
msgid "LDAP encoding error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:338
msgid "LDAP local error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:339
msgid "Cannot contact LDAP server"
msgstr ""

#: ../duplicity/gpg_error_codes.py:340
msgid "LDAP success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:341
msgid "LDAP operations error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:342
msgid "LDAP protocol error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:343
msgid "Time limit exceeded in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:344
msgid "Size limit exceeded in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:345
msgid "LDAP compare false"
msgstr ""

#: ../duplicity/gpg_error_codes.py:346
msgid "LDAP compare true"
msgstr ""

#: ../duplicity/gpg_error_codes.py:347
msgid "LDAP authentication method not supported"
msgstr ""

#: ../duplicity/gpg_error_codes.py:348
msgid "Strong(er) LDAP authentication required"
msgstr ""

#: ../duplicity/gpg_error_codes.py:349
msgid "Partial LDAP results+referral received"
msgstr ""

#: ../duplicity/gpg_error_codes.py:350
msgid "LDAP referral"
msgstr ""

#: ../duplicity/gpg_error_codes.py:351
msgid "Administrative LDAP limit exceeded"
msgstr ""

#: ../duplicity/gpg_error_codes.py:352
msgid "Critical LDAP extension is unavailable"
msgstr ""

#: ../duplicity/gpg_error_codes.py:353
msgid "Confidentiality required by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:354
msgid "LDAP SASL bind in progress"
msgstr ""

#: ../duplicity/gpg_error_codes.py:355
msgid "No such LDAP attribute"
msgstr ""

#: ../duplicity/gpg_error_codes.py:356
msgid "Undefined LDAP attribute type"
msgstr ""

#: ../duplicity/gpg_error_codes.py:357
msgid "Inappropriate matching in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:358
msgid "Constraint violation in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:359
msgid "LDAP type or value exists"
msgstr ""

#: ../duplicity/gpg_error_codes.py:360
msgid "Invalid syntax in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:361
msgid "No such LDAP object"
msgstr ""

#: ../duplicity/gpg_error_codes.py:362
msgid "LDAP alias problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:363
msgid "Invalid DN syntax in LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:364
msgid "LDAP entry is a leaf"
msgstr ""

#: ../duplicity/gpg_error_codes.py:365
msgid "LDAP alias dereferencing problem"
msgstr ""

#: ../duplicity/gpg_error_codes.py:366
msgid "LDAP proxy authorization failure (X)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:367
msgid "Inappropriate LDAP authentication"
msgstr ""

#: ../duplicity/gpg_error_codes.py:368
msgid "Invalid LDAP credentials"
msgstr ""

#: ../duplicity/gpg_error_codes.py:369
msgid "Insufficient access for LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:370
msgid "LDAP server is busy"
msgstr ""

#: ../duplicity/gpg_error_codes.py:371
msgid "LDAP server is unavailable"
msgstr ""

#: ../duplicity/gpg_error_codes.py:372
msgid "LDAP server is unwilling to perform"
msgstr ""

#: ../duplicity/gpg_error_codes.py:373
msgid "Loop detected by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:374
msgid "LDAP naming violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:375
msgid "LDAP object class violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:376
msgid "LDAP operation not allowed on non-leaf"
msgstr ""

#: ../duplicity/gpg_error_codes.py:377
msgid "LDAP operation not allowed on RDN"
msgstr ""

#: ../duplicity/gpg_error_codes.py:378
msgid "Already exists (LDAP)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:379
msgid "Cannot modify LDAP object class"
msgstr ""

#: ../duplicity/gpg_error_codes.py:380
msgid "LDAP results too large"
msgstr ""

#: ../duplicity/gpg_error_codes.py:381
msgid "LDAP operation affects multiple DSAs"
msgstr ""

#: ../duplicity/gpg_error_codes.py:382
msgid "Virtual LDAP list view error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:383
msgid "Other LDAP error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:384
msgid "Resources exhausted in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:385
msgid "Security violation in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:386
msgid "Invalid data in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:387
msgid "Unsupported scheme in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:388
msgid "Reload required in LCUP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:389
msgid "LDAP cancelled"
msgstr ""

#: ../duplicity/gpg_error_codes.py:390
msgid "No LDAP operation to cancel"
msgstr ""

#: ../duplicity/gpg_error_codes.py:391
msgid "Too late to cancel LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:392
msgid "Cannot cancel LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:393
msgid "LDAP assertion failed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:394
msgid "Proxied authorization denied by LDAP"
msgstr ""

#: ../duplicity/gpg_error_codes.py:395
msgid "SQL success"
msgstr ""

#: ../duplicity/gpg_error_codes.py:396
msgid "SQL error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:397
msgid "Internal logic error in SQL library"
msgstr ""

#: ../duplicity/gpg_error_codes.py:398
msgid "Access permission denied (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:399
msgid "SQL abort was requested"
msgstr ""

#: ../duplicity/gpg_error_codes.py:400
msgid "SQL database file is locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:401
msgid "An SQL table in the database is locked"
msgstr ""

#: ../duplicity/gpg_error_codes.py:402
msgid "SQL library ran out of core"
msgstr ""

#: ../duplicity/gpg_error_codes.py:403
msgid "Attempt to write a readonly SQL database"
msgstr ""

#: ../duplicity/gpg_error_codes.py:404
msgid "SQL operation terminated by interrupt"
msgstr ""

#: ../duplicity/gpg_error_codes.py:405
msgid "I/O error during SQL operation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:406
msgid "SQL database disk image is malformed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:407
msgid "Unknown opcode in SQL file control"
msgstr ""

#: ../duplicity/gpg_error_codes.py:408
msgid "Insertion failed because SQL database is full"
msgstr ""

#: ../duplicity/gpg_error_codes.py:409
msgid "Unable to open the SQL database file"
msgstr ""

#: ../duplicity/gpg_error_codes.py:410
msgid "SQL database lock protocol error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:411
msgid "(internal SQL code: empty)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:412
msgid "SQL database schema changed"
msgstr ""

#: ../duplicity/gpg_error_codes.py:413
msgid "String or blob exceeds size limit (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:414
msgid "SQL abort due to constraint violation"
msgstr ""

#: ../duplicity/gpg_error_codes.py:415
msgid "Data type mismatch (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:416
msgid "SQL library used incorrectly"
msgstr ""

#: ../duplicity/gpg_error_codes.py:417
msgid "SQL library uses unsupported OS features"
msgstr ""

#: ../duplicity/gpg_error_codes.py:418
msgid "Authorization denied (SQL)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:419
msgid "(unused SQL code: format)"
msgstr ""

#: ../duplicity/gpg_error_codes.py:420
msgid "SQL bind parameter out of range"
msgstr ""

#: ../duplicity/gpg_error_codes.py:421
msgid "File opened that is not an SQL database file"
msgstr ""

#: ../duplicity/gpg_error_codes.py:422
msgid "Notifications from SQL logger"
msgstr ""

#: ../duplicity/gpg_error_codes.py:423
msgid "Warnings from SQL logger"
msgstr ""

#: ../duplicity/gpg_error_codes.py:424
msgid "SQL has another row ready"
msgstr ""

#: ../duplicity/gpg_error_codes.py:425
msgid "SQL has finished executing"
msgstr ""

#: ../duplicity/gpg_error_codes.py:426
msgid "System error w/o errno"
msgstr ""

#: ../duplicity/gpg_error_codes.py:427
msgid "Unknown system error"
msgstr ""

#: ../duplicity/gpg_error_codes.py:428
msgid "End of file"
msgstr ""

#: ../duplicity/manifest.py:99
#, python-format
msgid "Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr "Критическая ошибка: Узел источника резервной копии изменён.\n"
"Текущий узел: %s\n"
"Предыдущий узел: %s"

#: ../duplicity/manifest.py:106
#, python-format
msgid "Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr "Критическая ошибка: Исходный каталог резервной копии был изменён.\n"
"Текущий каталог: %s\n"
"Предыдущий каталон: %s"

#: ../duplicity/manifest.py:116
msgid "Aborting because you may have accidentally tried to backup two different data sets to the same remote location, or using the same archive directory.  If this is not a mistake, use the --allow-source-mismatch switch to avoid seeing this message"
msgstr "Прекращение в связи с тем, что вы можете случайно попытаться создать резервные копии двух отличающихся наборов данных, по одному адресу, в одно и тоже удалённое расположение.  Если это ошибка, используйте параметр --allow-source-mismatch для скрытия этого сообщения"

#: ../duplicity/manifest.py:218
#, python-format
msgid "Found manifest volume %s"
msgstr ""

#: ../duplicity/manifest.py:225
#, python-format
msgid "Found %s volumes in manifest"
msgstr ""

#: ../duplicity/manifest.py:243
#, python-format
msgid "Manifest file '%s' is corrupt: File count says %d, File list contains %d"
msgstr ""

#: ../duplicity/manifest.py:262
msgid "Manifests not equal because different volume numbers"
msgstr "Манифесты не одинаковы в связи с отличающимися номерами томов"

#: ../duplicity/manifest.py:267
msgid "Manifests not equal because volume lists differ"
msgstr "Манифесты не одинаковы в связи с отличающимися списками томов"

#: ../duplicity/manifest.py:272
msgid "Manifests not equal because hosts or directories differ"
msgstr "Манифесты не одинаковы в связи с отличающимися узлами или каталогами"

#: ../duplicity/manifest.py:429
msgid "Warning, found extra Volume identifier"
msgstr "Внимание, найден дополнительный идентификатор тома"

#: ../duplicity/manifest.py:455
msgid "Other is not VolumeInfo"
msgstr "Другой не является VolumeInfo"

#: ../duplicity/manifest.py:458
msgid "Volume numbers don't match"
msgstr "Номера томов не соответствуют"

#: ../duplicity/manifest.py:461
msgid "start_indicies don't match"
msgstr "start_indicies не соответствует"

#: ../duplicity/manifest.py:464
msgid "end_index don't match"
msgstr "end_index не соответствует"

#: ../duplicity/manifest.py:471
msgid "Hashes don't match"
msgstr "Хэши не совпадают"

#: ../duplicity/util.py:159 ../duplicity/dup_main.py:847
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr "IGNORED_ERROR: Внимание: пропуск ошибки, как было обозначено в запросе: %s: %s"

#: ../duplicity/util.py:226
#, python-format
msgid "Releasing lockfile %s"
msgstr ""

#: ../duplicity/backends/pydrivebackend.py:181
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr ""

#: ../duplicity/backends/multibackend.py:96
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:105
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:160
#: ../duplicity/backends/multibackend.py:165
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:176
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:180
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: use store %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:194
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:207
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:248
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr ""

#: ../duplicity/backends/multibackend.py:261
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:268
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr ""

#: ../duplicity/backends/multibackend.py:275
#, python-format
msgid "MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:297
#, python-format
msgid "MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:307
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:310
#, python-format
msgid "Exception during list of %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:317
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:346
#: ../duplicity/backends/multibackend.py:375
#, python-format
msgid "MultiBackend: failed to delete %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/giobackend.py:109
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Не удалось подключиться, проверьте пароль: %s"

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:85
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:106
msgid "Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:110
#, python-format
msgid "For certificate verification with python 2.7.8 or earlier a cacert database\n"
"file is needed in one of these locations: %s\n"
"Hints:\n"
"Consult the man page, chapter 'SSL Certificate Verification'.\n"
"Consider using the options --ssl-cacert-file, --ssl-no-check-certificate ."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:168
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:170
#, python-format
msgid "Using WebDAV directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:201
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:212
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:231
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:232
#: ../duplicity/backends/webdavbackend.py:255
#, python-format
msgid "WebDAV data length: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:235
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:241
#, python-format
msgid "WebDAV redirect to: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:243
msgid "WebDAV redirected 10 times. Giving up."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:248
msgid "WebDAV missing location header in redirect response."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:253
msgid "WebDAV retry request with authentification headers."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:254
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:258
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:275
msgid "python-kerberos needed to use kerberos                           authorization, falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:279
#, python-format
msgid "Kerberos authorization failed: %s.                          Falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:377
#, python-format
msgid "Creating missing directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:394
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:439
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:461
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:481
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr ""

#: ../duplicity/diffdir.py:115 ../duplicity/diffdir.py:418
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Ошибка %s при получении различий для %s"

#: ../duplicity/diffdir.py:130
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Приём дельты %s и %s"

#: ../duplicity/diffdir.py:181
#, python-format
msgid "A %s"
msgstr "Д %s"

#: ../duplicity/diffdir.py:188
#, python-format
msgid "M %s"
msgstr "И %s"

#: ../duplicity/diffdir.py:210
#, python-format
msgid "Comparing %s and %s"
msgstr "Сравнение %s и %s"

#: ../duplicity/diffdir.py:218
#, python-format
msgid "D %s"
msgstr "У %s"

#: ../duplicity/commandline.py:78
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in version 0.9.0.\n"
"Use of default filenames is strongly suggested."
msgstr ""

#: ../duplicity/commandline.py:85
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in a future release.\n"
"--include-filelist and --exclude-filelist now accept globbing characters and should be used instead."
msgstr ""

#: ../duplicity/commandline.py:95
#, python-format
msgid "Warning: Option %s is pending deprecation and will be removed in a future release.\n"
"On many GNU/Linux systems, stdin is represented by /dev/stdin and\n"
"--include-filelist=/dev/stdin or --exclude-filelist=/dev/stdin could\n"
"be used as a substitute."
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:262 ../duplicity/commandline.py:272
#: ../duplicity/commandline.py:293 ../duplicity/commandline.py:364
#: ../duplicity/commandline.py:382 ../duplicity/commandline.py:393
#: ../duplicity/commandline.py:641 ../duplicity/commandline.py:689
#: ../duplicity/commandline.py:917
msgid "path"
msgstr "путь"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:288 ../duplicity/commandline.py:295
#: ../duplicity/commandline.py:388 ../duplicity/commandline.py:622
#: ../duplicity/commandline.py:890
msgid "gpg-key-id"
msgstr ""

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/commandline.py:303 ../duplicity/commandline.py:416
#: ../duplicity/commandline.py:940
msgid "shell_pattern"
msgstr ""

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:309 ../duplicity/commandline.py:318
#: ../duplicity/commandline.py:325 ../duplicity/commandline.py:418
#: ../duplicity/commandline.py:425 ../duplicity/commandline.py:438
#: ../duplicity/commandline.py:886
msgid "filename"
msgstr "имя файла"

#. Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:332 ../duplicity/commandline.py:429
msgid "regular_expression"
msgstr ""

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:336 ../duplicity/commandline.py:376
#: ../duplicity/commandline.py:516 ../duplicity/commandline.py:972
msgid "time"
msgstr "время"

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:384 ../duplicity/commandline.py:493
#: ../duplicity/commandline.py:519 ../duplicity/commandline.py:630
#: ../duplicity/commandline.py:905
msgid "options"
msgstr "параметры"

#: ../duplicity/commandline.py:402
#, python-format
msgid "Running in 'ignore errors' mode due to %s; please re-consider if this was not intended"
msgstr "Выполнение в режиме 'пропуска ошибок' в связи с %s; пожалуйста, пересмотрите решение, если это не было намерением"

#. Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:414
msgid "imap_mailbox"
msgstr ""

#: ../duplicity/commandline.py:432
msgid "file_descriptor"
msgstr ""

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:447 ../duplicity/commandline.py:469
#: ../duplicity/commandline.py:490 ../duplicity/commandline.py:496
#: ../duplicity/commandline.py:502 ../duplicity/commandline.py:555
#: ../duplicity/commandline.py:560 ../duplicity/commandline.py:564
#: ../duplicity/commandline.py:587 ../duplicity/commandline.py:593
#: ../duplicity/commandline.py:597 ../duplicity/commandline.py:671
#: ../duplicity/commandline.py:684 ../duplicity/commandline.py:697
#: ../duplicity/commandline.py:900
msgid "number"
msgstr "количество"

#. Used in usage help (noun)
#: ../duplicity/commandline.py:450
msgid "backup name"
msgstr "название резервной копии"

#: ../duplicity/commandline.py:582
msgid "policy"
msgstr ""

#: ../duplicity/commandline.py:600
msgid "Hot|Cool|Archive"
msgstr ""

#. noun
#: ../duplicity/commandline.py:603 ../duplicity/commandline.py:606
#: ../duplicity/commandline.py:871
msgid "command"
msgstr "команда"

#: ../duplicity/commandline.py:609
msgid "pyrax|cloudfiles"
msgstr ""

#: ../duplicity/commandline.py:633
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#: ../duplicity/commandline.py:634
msgid "path to a folder with certificate authority files"
msgstr ""

#: ../duplicity/commandline.py:638
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr ""

#. Used in usage help. Example:
#. --timeout <seconds>
#. Used in usage help. Example:
#. --backend-retry-delay <seconds>
#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:646 ../duplicity/commandline.py:702
#: ../duplicity/commandline.py:934
msgid "seconds"
msgstr "секунды"

#. abbreviation for "character" (noun)
#: ../duplicity/commandline.py:652 ../duplicity/commandline.py:868
msgid "char"
msgstr "символ"

#: ../duplicity/commandline.py:834
#, python-format
msgid "Using archive dir: %s"
msgstr "Использование каталога архива: %s"

#: ../duplicity/commandline.py:835
#, python-format
msgid "Using backup name: %s"
msgstr "Использование наименования резервной копии: %s"

#: ../duplicity/commandline.py:842
#, python-format
msgid "Command line error: %s"
msgstr "Ошибка в командной строке: %s"

#: ../duplicity/commandline.py:843
msgid "Enter 'duplicity --help' for help screen."
msgstr "Введите  'duplicity --help' для экрана справки."

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:856
msgid "absolute_path"
msgstr "полный_путь"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:860
msgid "alias"
msgstr "псевдоним"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:865
msgid "bucket_name"
msgstr ""

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:876
msgid "container_name"
msgstr ""

#. noun
#: ../duplicity/commandline.py:879
msgid "count"
msgstr "количество"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:882
msgid "directory"
msgstr "каталог"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:895
msgid "module"
msgstr "модуль"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:909
msgid "other.host"
msgstr ""

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:913
msgid "password"
msgstr "пароль"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:921
msgid "port"
msgstr "порт"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:926
msgid "prefix"
msgstr "префикс"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:930
msgid "relative_path"
msgstr "относительный_путь"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:945
msgid "some_dir"
msgstr "некоторый_каталог"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:951
msgid "source_dir"
msgstr ""

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:956
msgid "source_url"
msgstr ""

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:962
msgid "target_dir"
msgstr ""

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:967
msgid "target_url"
msgstr ""

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:977
msgid "user"
msgstr "пользователь"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/commandline.py:980
msgid "account_id"
msgstr ""

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/commandline.py:984
msgid "application_key"
msgstr ""

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/commandline.py:988 ../duplicity/dup_collections.py:517
msgid "remote"
msgstr "удалённая"

#. Header in usage help
#: ../duplicity/commandline.py:1007
msgid "Backends and their URL formats:"
msgstr "Заглушки и формат их URL:"

#. Header in usage help
#: ../duplicity/commandline.py:1045
msgid "Commands:"
msgstr "Команды:"

#: ../duplicity/commandline.py:1072
#, python-format
msgid "Specified archive directory '%s' does not exist, or is not a directory"
msgstr "Заданная папка архива '%s' не существует или не является папкой"

#: ../duplicity/commandline.py:1081
#, python-format
msgid "Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""

#: ../duplicity/commandline.py:1141
#, python-format
msgid "Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr "Каталог в который предназначено восстановление %s уже существует.\n"
"Замена не будет произведена."

#: ../duplicity/commandline.py:1146
#, python-format
msgid "Verify directory %s does not exist"
msgstr "Убедитесь, что папка %s не существует"

#: ../duplicity/commandline.py:1152
#, python-format
msgid "Backup source directory %s does not exist."
msgstr "Папка источника резервной копии %s не существует."

#: ../duplicity/commandline.py:1183
#, python-format
msgid "Command line warning: %s"
msgstr "Предупреждение командной строки: %s"

#: ../duplicity/commandline.py:1183
msgid "Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr "Параметры выбора --exclude/--include\n"
"в настоящее время работают только для резервного копирования, не для восстановления."

#: ../duplicity/commandline.py:1219
#, python-format
msgid "GPG binary is %s, version %s"
msgstr ""

#: ../duplicity/commandline.py:1246
#, python-format
msgid "Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr "Недопустимая адресная ссылка URL '%s'.\n"
"Например: \"scp://user@host.net:1234/path\" и\n"
"\"file:///usr/local\".  Для получения дополнительных сведений обратитесь в руководству (man)."

#: ../duplicity/commandline.py:1276
msgid "Main action: "
msgstr "Главное действие: "

#: ../duplicity/librsync.py:196
msgid "basis_file must be a (true) file or an object whose file attribute is the underlying true file object"
msgstr ""

#: ../duplicity/dup_time.py:63
#, python-format
msgid "Bad interval string \"%s\"\n\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr "Строка с недопустимым интервалом \"%s\"\n\n"
"Интервалы задаются на подобии 2Y (2 года) или 2h30m (2.5 часа).\n"
"Допустимые особые символы s (с.), m (м.), h (ч.), D(Д.), W (Н.), M (М.) и Y (Г.).  \n"
"Обратитесь к руководству пользователя (man) для получения дополнительных сведений."

#: ../duplicity/dup_time.py:69
#, python-format
msgid "Bad time string \"%s\"\n\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr "Строка с недопустимым временем \"%s\"\n\n"
"Допускается задание интервалов времени (например \"3D64s\"), строки \n"
"даты/времени формата w3, например \"2002-04-26T04:22:01-07:00\" (строки типа\n"
"\"2002-04-26T04:22:01\" также допустимы - duplicity будет использовать\n"
"текущую временную зону) или обычные даты, например 2/4/1997 или 2001-04-23\n"
"(допустимы различные комбинации, но месяц всегда предшествует дню)."

#: ../duplicity/dup_main.py:120
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Повторное использование настроенного PASSPHRASE как SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:127
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Повторное использование настроенного SIGN_PASSPHRASE как PASSPHRASE"

#: ../duplicity/dup_main.py:168
msgid "PASSPHRASE variable not set, asking user."
msgstr "Переменная PASSPHRASE не назначена, выполняется запрос пользователя."

#: ../duplicity/dup_main.py:183
msgid "GnuPG passphrase for signing key:"
msgstr "Кодовая фраза GnuPG для подписывающего ключа:"

#: ../duplicity/dup_main.py:188
msgid "GnuPG passphrase for decryption:"
msgstr ""

#: ../duplicity/dup_main.py:193
msgid "Retype passphrase for signing key to confirm: "
msgstr "Введите повторно кодовую фразу для подписывающего ключа: "

#: ../duplicity/dup_main.py:195
msgid "Retype passphrase for decryption to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:198
msgid "First and second passphrases do not match!  Please try again."
msgstr "Первая и вторая кодовая фраза не совпадают! Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:205
msgid "Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr "Невозможно использовать пустую кодовую фразу с симметричным шифрованием!  Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:263
#, python-format
msgid "File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr "Файл %s уже имеется в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:272
#, python-format
msgid "File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr "Файл %s отсутствует в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:326
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d, retrying."
msgstr ""

#: ../duplicity/dup_main.py:331
#, python-format
msgid "File %s was corrupted during upload."
msgstr "Файл %s был повреждён во время выгрузки."

#: ../duplicity/dup_main.py:371
msgid "Restarting backup, but current encryption settings do not match original settings"
msgstr "Перезапуск резервного копирования, но настройки текущего шифрования не соответствуют исходным настройкам"

#: ../duplicity/dup_main.py:394
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr ""

#: ../duplicity/dup_main.py:397
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr ""

#: ../duplicity/dup_main.py:475
#, python-format
msgid "Processed volume %d"
msgstr ""

#: ../duplicity/dup_main.py:625
msgid "Fatal Error: Unable to start incremental backup.  Old signatures not found and incremental specified"
msgstr "Фатальная ошибка: Не удалось начать пошаговое резервное копирование. Старая сигнатура не найдена и указан пошаговый режим"

#: ../duplicity/dup_main.py:629
msgid "No signatures found, switching to full backup."
msgstr "Сигнатуры не найдены, переключение на полную резервную копию."

#: ../duplicity/dup_main.py:643
msgid "Backup Statistics"
msgstr "Статистика резервного копирования"

#: ../duplicity/dup_main.py:751
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "%s не найден в архиве, нет восстановленных файлов."

#: ../duplicity/dup_main.py:755
msgid "No files found in archive - nothing restored."
msgstr "Ничего не найдено в архиве - ничего не восстановлено."

#: ../duplicity/dup_main.py:792
#, python-format
msgid "Processed volume %d of %d"
msgstr "Обработан том %d из %d"

#: ../duplicity/dup_main.py:837
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "Недопустимые данные - %s hash не соответствует файлу:"

#: ../duplicity/dup_main.py:840
#, python-format
msgid "Calculated hash: %s"
msgstr "Вычисленный хэш: %s"

#: ../duplicity/dup_main.py:841
#, python-format
msgid "Manifest hash: %s"
msgstr "Хеш манифеста: %s"

#: ../duplicity/dup_main.py:892
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "Том был подписан ключом %s, а не %s"

#: ../duplicity/dup_main.py:924
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Проверка завершена: %s, %s."

#: ../duplicity/dup_main.py:925
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] "%d файл сравнён"
msgstr[1] "%d файла сравнены"
msgstr[2] "%d файлов сравнено"
msgstr[3] ""

#: ../duplicity/dup_main.py:927
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] "%d отличие найдено"
msgstr[1] "%d отличия найдено"
msgstr[2] "%d отличий найдено"
msgstr[3] ""

#: ../duplicity/dup_main.py:946
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Посторонних файлов не найдено, при очистке ничего не удалено."

#: ../duplicity/dup_main.py:951
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] "Удаляется следующий файл из заглушки:"
msgstr[1] "Удаляются следующие файлы из заглушки:"
msgstr[2] "Удаляются следующие файлы из заглушки:"
msgstr[3] ""

#: ../duplicity/dup_main.py:962
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] "Найден файл для удаления:"
msgstr[1] "Найдены файлы для удаления:"
msgstr[2] "Найдены файлы для удаления:"
msgstr[3] ""

#: ../duplicity/dup_main.py:965
msgid "Run duplicity again with the --force option to actually delete."
msgstr "Запустите duplicity ещё раз с ключом --force чтобы удалить на самом деле."

#: ../duplicity/dup_main.py:1008
msgid "There are backup set(s) at time(s):"
msgstr "Есть резервные копии за следующие даты:"

#: ../duplicity/dup_main.py:1010
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Какие не могут быть удалены из-за новых наборов зависящих от них."

#: ../duplicity/dup_main.py:1014
msgid "Current active backup chain is older than specified time.  However, it will not be deleted.  To remove all your backups, manually purge the repository."
msgstr "Текущая активная цепочка резервных копий старее чем указанное время.  Те не менее, она не будет удалена. Чтобы удалить все резервные копии, вручную очистите хранилище."

#: ../duplicity/dup_main.py:1027
msgid "No old backup sets found, nothing deleted."
msgstr "Старые резервные копии не найдены, ничего не удалено."

#: ../duplicity/dup_main.py:1030
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] "Удаление цепочки резервных копий по времени:"
msgstr[1] "Удаление цепочек резервных копий по времени:"
msgstr[2] "Удаление цепочек резервных копий по времени:"
msgstr[3] ""

#: ../duplicity/dup_main.py:1042
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1044
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1047
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Удаление всей цепочки подписей %s"

#: ../duplicity/dup_main.py:1049
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Удаление полной цепочки резервных копий  %s"

#: ../duplicity/dup_main.py:1055
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] "Обнаружена цепочка резервных копий, выполненных:"
msgstr[1] "Обнаружены цепочки резервных копий, выполненных:"
msgstr[2] "Обнаружены цепочки резервных копий, выполненных:"
msgstr[3] ""

#: ../duplicity/dup_main.py:1059
msgid "Rerun command with --force option to actually delete."
msgstr ""

#: ../duplicity/dup_main.py:1082
msgid "No old backup sets found."
msgstr ""

#: ../duplicity/dup_main.py:1097
#, python-format
msgid "Signature %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1104 ../duplicity/dup_main.py:1143
#, python-format
msgid "Replicating %s."
msgstr ""

#: ../duplicity/dup_main.py:1131
#, python-format
msgid "Backupset %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1279
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Удаление локального %s (недостаточно надёжный во внутреннем интерфейсе)."

#: ../duplicity/dup_main.py:1284
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Невозможно удалить %s: %s"

#: ../duplicity/dup_main.py:1318 ../duplicity/dup_temp.py:271
#, python-format
msgid "Failed to read %s: %s"
msgstr "Не удалось прочитать %s: %s"

#: ../duplicity/dup_main.py:1331
#, python-format
msgid "Copying %s to local cache."
msgstr "Копируется %s в локальный кэш."

#: ../duplicity/dup_main.py:1379
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr "Локальные и удалённые метаданные синхронизированы, синхронизация не требуется."

#: ../duplicity/dup_main.py:1384
msgid "Synchronizing remote metadata to local cache..."
msgstr "Синхронизация удалённых метаданных с локальными временными файлами..."

#: ../duplicity/dup_main.py:1397
msgid "Sync would copy the following from remote to local:"
msgstr "Синхронизация скопирует это из удаленного места в локальное:"

#: ../duplicity/dup_main.py:1400
msgid "Sync would remove the following spurious local files:"
msgstr "Синхронизация удалит следующие  неизвестные файлы:"

#: ../duplicity/dup_main.py:1444
msgid "Unable to get free space on temp."
msgstr "Не удалось узнать объем доступного пространства во временном каталоге."

#: ../duplicity/dup_main.py:1452
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr "Во временно каталоге доступного %d, для резервного копирования нужно примерно %d."

#: ../duplicity/dup_main.py:1455
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr "Во временном каталоге доступно %d, для резервного копирования будет использовано примерно %d."

#: ../duplicity/dup_main.py:1463
msgid "Unable to get max open files."
msgstr "Не удалось узнать максимальное количество открытых файлов."

#: ../duplicity/dup_main.py:1467
#, python-format
msgid "Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr "Максимальное количество открытых файлов %s слишком мало, Должно быть >= 1024.\n"
"Используйте 'ulimit -n 1024' или выше, чтобы исправить.\n"

#: ../duplicity/dup_main.py:1519
msgid "RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr "ПЕРЕЗАПУСК: Ошибка выгрузки первого тома перед завершением работы.\n"
"         Перезапуск невозможен...выполнение резервного копирования с начала."

#: ../duplicity/dup_main.py:1525
#, python-format
msgid "RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr "ПЕРЕЗАПУСК: Ошибка выгрузки томов %d дo %d перед завершением работы.\n"
"         Перезапуск резервного копирования в томе %d."

#: ../duplicity/dup_main.py:1532
#, python-format
msgid "RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last partial\n"
"         backup then restart the backup from the beginning."
msgstr "ПЕРЕЗАПУСК: Невозможное состояние резервной копии: манифест содержит %d томов, удалённый содержит %d томов.\n"
"         Перезапуск невозможен ... duplicity произведёт очистку последней части\n"
"         резервной копии, затем запустит резервное копирования сначала."

#: ../duplicity/dup_main.py:1553
msgid "\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1576
#, python-format
msgid "Acquiring lockfile %s"
msgstr ""

#: ../duplicity/dup_main.py:1639
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr "Последняя %s резервная копия оставила частичный набор, выполняется перезапуск."

#: ../duplicity/dup_main.py:1643
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr "Очистка предыдущего частичного %s набора резервного копирования, выполняется перезапуск."

#: ../duplicity/dup_main.py:1655
msgid "Last full backup date:"
msgstr "Время последней полной резервной копии:"

#: ../duplicity/dup_main.py:1657
msgid "Last full backup date: none"
msgstr "Время последней полной резервной копии: нету"

#: ../duplicity/dup_main.py:1660
msgid "Last full backup is too old, forcing full backup"
msgstr "Последняя полная резервная копия слишком старая, будет сделана полная резервная копия"

#: ../duplicity/dup_main.py:1709
msgid "When using symmetric encryption, the signing passphrase must equal the encryption passphrase."
msgstr "При использовании симметричного шифрования кодовая фраза для подписи должна совпадать с кодовой фразой для шифрования."

#: ../duplicity/asyncscheduler.py:70
#, python-format
msgid "instantiating at concurrency %d"
msgstr "параллельное создание %d"

#: ../duplicity/asyncscheduler.py:97
msgid "inserting barrier"
msgstr "вставка барьера"

#: ../duplicity/asyncscheduler.py:146
msgid "running task synchronously (asynchronicity disabled)"
msgstr "выполнение задачи синхронно (асинхронность выключена)"

#: ../duplicity/asyncscheduler.py:152
msgid "scheduling task for asynchronous execution"
msgstr "Планирование задачи для асинхронного выполнения"

#: ../duplicity/asyncscheduler.py:181
msgid "task completed successfully"
msgstr "задача успешно завершена"

#: ../duplicity/asyncscheduler.py:192
msgid "a previously scheduled task has failed; propagating the result immediately"
msgstr "не удалось выполнить запланированную ранее задачу; выполняется мгновенное распространение результата"

#: ../duplicity/asyncscheduler.py:215 ../duplicity/asyncscheduler.py:236
#, python-format
msgid "active workers = %d"
msgstr "активный обработчики = %d"

#: ../duplicity/asyncscheduler.py:256
#, python-format
msgid "task execution done (success: %s)"
msgstr "завершено выполнение задачи (успех: %s)"

#: ../duplicity/gpginterface.py:240
msgid "Threading not available -- zombie processes may appear"
msgstr ""

#: ../duplicity/gpginterface.py:707
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr "Процесс GPG %d завершился до вызова wait()"

#: ../duplicity/robust.py:64
#, python-format
msgid "Error listing directory %s"
msgstr "Ошибка перечня каталога %s"

#: ../duplicity/dup_collections.py:186 ../duplicity/dup_collections.py:200
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/dup_collections.py:225
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "Критическая ошибка: отсутствуют манифесты для недавней резервной копии"

#: ../duplicity/dup_collections.py:234
msgid "Fatal Error: Remote manifest does not match local one.  Either the remote backup set or the local archive directory has been corrupted."
msgstr "Критическая ошибка: Удалённый манифест не соответствует локальному. Неисправен удалённый набор резервного копирования или папка локального архива."

#: ../duplicity/dup_collections.py:242
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Критическая ошибка: Нет доступа к чтению удалённого и локального манифеста."

#: ../duplicity/dup_collections.py:253
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:265
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr ""

#: ../duplicity/dup_collections.py:268
#, python-format
msgid "Processing remote manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:364
msgid "Preferring Backupset over previous one!"
msgstr "Предпочтение набора резервного копирования вместо предыдущего!"

#: ../duplicity/dup_collections.py:367
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr "Пропуск инкрементального  набора резервного копирования (время_запуска: %s; необходимо: %s)"

#: ../duplicity/dup_collections.py:372
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr "Добавлена пошаговая резервная копия (время_начала: %s / время_конца: %s)"

#: ../duplicity/dup_collections.py:442
msgid "Chain start time: "
msgstr "Цепочка начата: "

#: ../duplicity/dup_collections.py:443
msgid "Chain end time: "
msgstr "Цепочка завершена: "

#: ../duplicity/dup_collections.py:444
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Количество содержащихся наборов резервного копирования: %d"

#: ../duplicity/dup_collections.py:446
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Общее число содержащихся томов: %d"

#: ../duplicity/dup_collections.py:448 ../duplicity/dup_collections.py:1247
msgid "Type of backup set:"
msgstr "Тип резервной копии:"

#: ../duplicity/dup_collections.py:448 ../duplicity/dup_collections.py:1247
msgid "Time:"
msgstr "Время:"

#: ../duplicity/dup_collections.py:448
msgid "Num volumes:"
msgstr "Число томов:"

#: ../duplicity/dup_collections.py:452 ../duplicity/dup_collections.py:1253
msgid "Full"
msgstr "Полная"

#: ../duplicity/dup_collections.py:455 ../duplicity/dup_collections.py:1255
msgid "Incremental"
msgstr "Пошаговая"

#: ../duplicity/dup_collections.py:515
msgid "local"
msgstr "Локальная"

#: ../duplicity/dup_collections.py:672
msgid "Collection Status"
msgstr "Состояние сбора"

#: ../duplicity/dup_collections.py:674
#, python-format
msgid "Connecting with backend: %s"
msgstr "Соединение с внутренним интерфейсом: %s"

#: ../duplicity/dup_collections.py:676
#, python-format
msgid "Archive dir: %s"
msgstr "Папка архива: %s"

#: ../duplicity/dup_collections.py:679
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] "Найдена %d вторичная цепочка резервных копий."
msgstr[1] "Найдены %d вторичные цепочки резервных копий."
msgstr[2] "Найдено %d вторичных цепочек резервных копий."
msgstr[3] ""

#: ../duplicity/dup_collections.py:684
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Вторичная цепочка %d из %d:"

#: ../duplicity/dup_collections.py:690
msgid "Found primary backup chain with matching signature chain:"
msgstr "Найдена первичная цепочка резервного копирования с соответствующей цепочкой подписи:"

#: ../duplicity/dup_collections.py:694
msgid "No backup chains with active signatures found"
msgstr "Отсутствуют цепочки резервного копирования с найденными, задействованными подписями"

#: ../duplicity/dup_collections.py:697
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] "Также найден %d набор резервного копирования, не являющегося частью ни одной цепочки,"
msgstr[1] "Также найдены %d набора резервного копирования, не являющихся частью ни одной цепочки,"
msgstr[2] "Также найдены %d наборов резервного копирования, не являющихся частью ни одной цепочки,"
msgstr[3] ""

#: ../duplicity/dup_collections.py:701
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] "а также %d неполный набор резервного копирования."
msgstr[1] "а также %d неполных набора резервного копирования."
msgstr[2] "а также %d неполных наборов резервного копирования."
msgstr[3] ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:706
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "Это может быть удалено с помощью запуска duplicity с командой \"cleanup\"."

#: ../duplicity/dup_collections.py:709
msgid "No orphaned or incomplete backup sets found."
msgstr "Отсутствуют изолированные или неполные наборы резервного копирования."

#: ../duplicity/dup_collections.py:725
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] "%d файл существует во внутреннем интерфейсе"
msgstr[1] "%d файлов существует во внутреннем интерфейсе"
msgstr[2] "%d файлов существует во внутреннем интерфейсе"
msgstr[3] ""

#: ../duplicity/dup_collections.py:735
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "%d файл существует во временных файлах"
msgstr[1] "%d файла существует во временных файлах"
msgstr[2] "%d файлов существует во временных файлах"
msgstr[3] ""

#: ../duplicity/dup_collections.py:788
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr "Внимание, отозван последний набор резервного копирования, в связи с отсутствием файла подписи."

#: ../duplicity/dup_collections.py:811
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] "Внимание, найден следующий локальный изолированный файл подписи:"
msgstr[1] "Внимание, найдены следующие локальные изолированные файлы подписей:"
msgstr[2] "Внимание, найдены следующие локальные изолированные файлы подписей:"
msgstr[3] ""

#: ../duplicity/dup_collections.py:820
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] "Внимание, найден следующий удалённый изолированный файл подписи:"
msgstr[1] "Внимание, найдены следующие удалённые изолированные файлы подписей:"
msgstr[2] "Внимание, найдены следующие удалённые изолированные файлы подписей:"
msgstr[3] ""

#: ../duplicity/dup_collections.py:829
msgid "Warning, found signatures but no corresponding backup files"
msgstr "Внимание, найдены подписи, которые не соответствуют с файлами резервной копии"

#: ../duplicity/dup_collections.py:833
msgid "Warning, found incomplete backup sets, probably left from aborted session"
msgstr "Внимание, обнаружены незавершённые наборы резервных копий, возможно они остались от прерванного сеанса"

#: ../duplicity/dup_collections.py:837
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] "Внимание, найден следующий изолированный файл резервного копирования:"
msgstr[1] "Внимание, найдены следующие изолированные файлы резервного копирования:"
msgstr[2] "Внимание, найдены следующие изолированные файлы резервного копирования:"
msgstr[3] ""

#: ../duplicity/dup_collections.py:854
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Извлечение цепочек резервного копирования из списка файлов: %s"

#: ../duplicity/dup_collections.py:866
#, python-format
msgid "File %s is part of known set"
msgstr "Файл %s является частью известного набора"

#: ../duplicity/dup_collections.py:869
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "Файл %s не является частью известного набора; создаётся новый набор"

#: ../duplicity/dup_collections.py:874
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Пропуск файла (отклонено набором резервного копирования) '%s'"

#: ../duplicity/dup_collections.py:890
#, python-format
msgid "Found backup chain %s"
msgstr "Найдена резервная копия %s"

#: ../duplicity/dup_collections.py:895
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "Добавление набора %s для ранее существующей цепочки %s"

#: ../duplicity/dup_collections.py:899
#, python-format
msgid "Found orphaned set %s"
msgstr "Обнаружен изолированный набор %s"

#: ../duplicity/dup_collections.py:1049
#, python-format
msgid "No signature chain for the requested time. Using oldest available chain, starting at time %s."
msgstr ""

#: ../duplicity/dup_collections.py:1245
#, python-format
msgid "File: %s"
msgstr "Файл: %s"

#: ../duplicity/dup_collections.py:1246
#, python-format
msgid "Total number of backup: %d"
msgstr "Общее количество резервного копирования: %d"

#: ../duplicity/dup_collections.py:1247 ../duplicity/dup_collections.py:1273
msgid "Type of file change:"
msgstr "Тип изменения файла:"

#: ../duplicity/dup_collections.py:1271
#, python-format
msgid " Backup set time: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1272
#, python-format
msgid "Total number of changes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1273
msgid "File:"
msgstr ""

#: ../duplicity/patchdir.py:83 ../duplicity/patchdir.py:88
#, python-format
msgid "Patching %s"
msgstr "Внесение изменений в %s"

#: ../duplicity/patchdir.py:557
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:632
#, python-format
msgid "Writing %s of type %s"
msgstr "Запись %s типа %s"

#: ../duplicity/selection.py:117
#, python-format
msgid "Skipping socket %s"
msgstr "Пропуск сокета %s"

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr "Ошибка инициализации файла %s"

#: ../duplicity/selection.py:125 ../duplicity/selection.py:150
#: ../duplicity/selection.py:455
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Ошибка доступа к возможно заблокированному файлу %s"

#: ../duplicity/selection.py:165
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Внимание: база %s не существует, выполняется продолжение"

#: ../duplicity/selection.py:168 ../duplicity/selection.py:186
#: ../duplicity/selection.py:189
#, python-format
msgid "Selecting %s"
msgstr "Выбор %s"

#: ../duplicity/selection.py:286
#, python-format
msgid "Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr "Критическая ошибка: Спецификация файла\n"
"    %s\n"
"не может соответствовать любым файлам в базовом каталоге\n"
"    %s\n"
"Полезные спецификации файла начинаются с базового каталога или\n"
"маски (например '**'), которая соответствует базовому каталогу."

#: ../duplicity/selection.py:295
#, python-format
msgid "Fatal Error while processing expression\n"
"%s"
msgstr "Критическая ошибка при обработке выражения\n"
"%s"

#: ../duplicity/selection.py:304
#, python-format
msgid "Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr "Выражение последнего выделения:\n"
"    %s\n"
"только указывает на то, что файлы будут включены.  Так как\n"
"по умолчанию включаются все файлы, следовательно выражение избыточно.  \n"
"Выполнение выхода, так как возможно, что вероятно, это не то, что вы имели в виду."

#: ../duplicity/selection.py:360
#, python-format
msgid "Reading globbing filelist %s"
msgstr "Чтение подстановочного списка файлов %s"

#: ../duplicity/selection.py:396
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Ошибка компилирования регулярного выражения %s"

#: ../duplicity/lazy.py:355
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Внимание: старый индекс %s >= нового индекса %s"

#: ../duplicity/lazy.py:430
#, python-format
msgid "Error '%s' processing %s"
msgstr "Ошибка '%s' при обработке %s"

#: ../duplicity/lazy.py:440
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Пропуск %s из-за предыдущей ошибки"

#: ../duplicity/path.py:115
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:245 ../duplicity/path.py:306
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Внимание: у %s отрицательное mtime, принимается равным 0."

#: ../duplicity/path.py:370
msgid "Difference found:"
msgstr "Найдено отличие:"

#: ../duplicity/path.py:379
#, python-format
msgid "New file %s"
msgstr "Новый файл %s"

#: ../duplicity/path.py:382
#, python-format
msgid "File %s is missing"
msgstr "Файл %s отсутствует"

#: ../duplicity/path.py:385
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "Файл %%s относится к типу %s, а ожидался %s"

#: ../duplicity/path.py:391 ../duplicity/path.py:417
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "Файл %%s имеет разрешения %s, а ожидалось %s"

#: ../duplicity/path.py:396
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "Файл %%s имеет mtime %s, а ожидалось %s"

#: ../duplicity/path.py:404
#, python-format
msgid "Data for file %s is different"
msgstr "Данные для файла %s отличаются"

#: ../duplicity/path.py:412
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "Символическая ссылка %%s указывает на %s, а ожидалось %s"

#: ../duplicity/path.py:421
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "Файл устройства %%s содержит номера %s, а ожидались %s"

#: ../duplicity/path.py:613
#, python-format
msgid "Making directory %s"
msgstr "Создаётся каталог %s"

#: ../duplicity/path.py:623
#, python-format
msgid "Deleting %s"
msgstr "Удаляется %s"

#: ../duplicity/path.py:632
#, python-format
msgid "Touching %s"
msgstr ""

#: ../duplicity/path.py:639
#, python-format
msgid "Deleting tree %s"
msgstr "Удаление дерева %s"

